// GENERATED by relay-server asset pass — do not edit by hand.
// Legacy location: the resources module now lives at lib/resources/assets.ts (CONTRACTS §5).
// Kept as a re-export so screens that import this path still resolve.
export * from '../../lib/resources/assets';
