// GENERATED by relay-server asset pass — do not edit by hand.
// Semantic names → bundled asset paths. Reference these instead of
// hard-coding strings or substituting Material icons.
//
// Declare the asset dirs in pubspec.yaml under flutter > assets.

class AppAssets {
  AppAssets._();

  static const String searchIcon = 'assets/icons/search_icon.svg';
  static const String mapDark = 'assets/images/map_dark.png';
  static const String promoBanner = 'assets/images/promo_banner.png';
  static const String userAvatar = 'assets/images/user_avatar.png';
}
