// =============================================================================
// File: src/relay-server/resources-emit.ts
//
// FRAMEWORK-AGNOSTIC asset RESOURCES generation (Phase-2 asset pass).
//
// Given the target framework + a set of localized assets (each with a semantic
// name + a project-relative path), emit ONE resources/constants file the agent
// references so screens stop hard-coding string paths / substituting Material
// icons. Nothing here is Flutter-specific: each framework registers a small
// `Emitter` in EMITTERS, and adding a framework = adding one entry.
//
//   flutter        → lib/resources/app_assets.dart   (class AppAssets {...})
//   react / next / → src/resources/assets.ts          (export const assets {...})
//   vite / web / ts
// =============================================================================

/** An asset to surface in the resources file. */
export interface ResourceAsset {
  /** semantic identifier, e.g. `add_circle` / `netflix_icon`. snake_case in. */
  name: string;
  /** project-relative asset path, e.g. `assets/icons/add_circle.svg`. */
  relPath: string;
  format: 'svg' | 'png';
  kind: 'icon' | 'image';
}

export interface EmittedResources {
  /** project-relative path of the file to write. */
  filePath: string;
  /** full file contents. */
  contents: string;
}

interface Emitter {
  filePath: string;
  emit(assets: ResourceAsset[]): string;
}

// ── name helpers ────────────────────────────────────────────────────────────
const toSnake = (s: string): string =>
  (s || 'asset')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase()
    .replace(/^_+|_+$/g, '')
    .replace(/^([0-9])/, '_$1') || 'asset';

const toLowerCamel = (s: string): string => {
  const snake = toSnake(s);
  const camel = snake.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  // Re-guard a leading digit: a Dart/TS identifier can't start with one (the
  // camel step strips the `_` toSnake prepended), so re-prefix.
  return /^[0-9]/.test(camel) ? `a${camel}` : (camel || 'asset');
};

/** Dedupe identifiers (two assets can normalize to the same key) by suffixing. */
function dedupeKeys<T>(items: T[], keyOf: (t: T) => string): Array<{ key: string; item: T }> {
  const used = new Map<string, number>();
  return items.map((item) => {
    let key = keyOf(item);
    const n = used.get(key) ?? 0;
    used.set(key, n + 1);
    if (n > 0) key = `${key}_${n + 1}`;
    return { key, item };
  });
}

// ── per-framework emitters ────────────────────────────────────────────────────

const flutterEmitter: Emitter = {
  filePath: 'lib/resources/app_assets.dart',
  emit(assets) {
    const entries = dedupeKeys(assets, (a) => toLowerCamel(a.name));
    const lines = entries.map(({ key, item }) =>
      `  static const String ${key} = '${item.relPath}';`);
    return [
      '// GENERATED by relay-server asset pass — do not edit by hand.',
      '// Semantic names → bundled asset paths. Reference these instead of',
      '// hard-coding strings or substituting Material icons.',
      '//',
      '// Declare the asset dirs in pubspec.yaml under flutter > assets.',
      '',
      'class AppAssets {',
      '  AppAssets._();',
      '',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

const tsEmitter = (filePath: string): Emitter => ({
  filePath,
  emit(assets) {
    const entries = dedupeKeys(assets, (a) => toLowerCamel(a.name));
    const body = entries.map(({ key, item }) =>
      `  ${key}: '${item.relPath}',`);
    return [
      '// GENERATED by relay-server asset pass — do not edit by hand.',
      '// Semantic names → bundled asset paths. Import `assets` and reference',
      '// these instead of hard-coding strings or substituting icon-font glyphs.',
      '',
      'export const assets = {',
      ...body,
      '} as const;',
      '',
      'export type AssetName = keyof typeof assets;',
      '',
    ].join('\n');
  },
});

/** Per-framework emitter registry. Extend by adding an entry. */
const EMITTERS: Record<string, Emitter> = {
  flutter: flutterEmitter,
  react: tsEmitter('src/resources/assets.ts'),
  next: tsEmitter('src/resources/assets.ts'),
  vite: tsEmitter('src/resources/assets.ts'),
  web: tsEmitter('src/resources/assets.ts'),
  ts: tsEmitter('src/resources/assets.ts'),
};

/** Frameworks we can emit a resources file for. */
export function canEmitResources(framework: string): boolean {
  return !!EMITTERS[(framework || '').toLowerCase()];
}

/**
 * Emit the resources/constants file for `framework` from `assets`. Returns the
 * project-relative path + the file contents (the caller writes it), or null when
 * the framework has no emitter or there are no assets.
 */
export function emitResources(framework: string, assets: ResourceAsset[]): EmittedResources | null {
  const emitter = EMITTERS[(framework || '').toLowerCase()];
  if (!emitter || assets.length === 0) return null;
  // Stable order: icons first, then images; alphabetical within each.
  const sorted = [...assets].sort((a, b) =>
    a.kind === b.kind ? a.name.localeCompare(b.name) : a.kind === 'icon' ? -1 : 1);
  return { filePath: emitter.filePath, contents: emitter.emit(sorted) };
}
