// =============================================================================
// File: src/relay-server/web-skeleton.ts
//
// GEN_PHASE 3 (Skeleton) for the web targets — the React (Vite + react-router) and
// Next.js (App Router) counterpart of canonicalize.ts → generateFlutterSkeleton.
//
// Every web pass (7a–7h) resolves screens, routes, placeholders and the theme from
// a contract: a `ROUTES` table, a react-router `<Routes>` (or the Next app dir), a
// `// canonicalId: <id> route: <route>` header on every screen, `PlaceholderScreen`
// for an unbuilt slot, `showModal_<core>()` + `modalController` for folded modals,
// and an `AppTheme` token object. Until this module existed nothing in the pipeline
// emitted any of it — the build agent was told to "create a central route table" in
// whatever shape it liked, and the passes worked only when an agent happened to
// invent this one (parity audit PG-02). This emits the contract deterministically,
// BEFORE screen 1 builds, from canonical.json:
//
//   react (Vite, CONTRACTS §5: pipeline files under src/)
//     src/router/routes.ts            ROUTES table + ENTRY_ROUTE (write-locked)
//     src/App.tsx                     <BrowserRouter><Routes> — one <Route> per canonical
//                                     screen, the tab cluster nested under <AppShell/>,
//                                     one verify route per frame at /_preview/<frame>
//     src/main.tsx                    entry → App + theme.css (only when missing/boilerplate)
//     src/shell/AppShell.tsx          the ONE shared tab bar (tab cluster only)
//     src/screens/<Class>.tsx         a header-stamped stub per canonical screen
//     src/modal/*                     modalController + ModalHost + a presenter stub per
//                                     folded modal (`showModal_<core>()`, fixed name)
//     src/_preview/<X>Preview.tsx     modal verify harness (auto-presents the modal)
//     src/components/PlaceholderScreen.tsx, src/theme/theme.{ts,css} (stubs)
//
//   next (App Router, CONTRACTS §5: pipeline files beside the app dir's parent `<root>`)
//     <root>/lib/routes.ts            ROUTES table + ENTRY_ROUTE
//     <root>/app/<route>/page.tsx     a header-stamped stub page per canonical screen
//                                     (the header sits ABOVE 'use client'); the tab
//                                     cluster lives in the `(tabs)` route group whose
//                                     layout renders <AppShell>
//     <root>/app/%5Fpreview/<frame>/page.tsx   verify routes — `/_preview/<frame>`. A
//                                     folder named `_preview` is a PRIVATE folder the
//                                     App Router never routes; `%5F` is the escape.
//     <root>/app/layout.tsx, app/page.tsx      root layout (theme.css + ModalHost) and a
//                                     redirect to the entry route (missing/boilerplate only)
//     <root>/components/*, <root>/lib/modal/modalController.ts, <root>/lib/theme/*
//
// An EMPTY project also gets the minimal toolchain files (package.json, tsconfig,
// vite/next config, index.html) so the skeleton builds on its own; an existing
// scaffold keeps its own and only gains what the contract needs (react-router-dom
// on react; `output: 'export'` on next — the verify harness serves a static export).
//
// Additive + idempotent, exactly like the Flutter skeleton: a built screen / modal
// file is NEVER clobbered; the write-locked contract files (route table, router,
// shell, previews) are regenerated only when missing, generated by us, or the
// framework's own untouched boilerplate — a hand-written file is left alone and
// reported in `kept`. Running it twice writes nothing the second time.
// =============================================================================

import * as fs from 'fs/promises';
import * as fsSync from 'fs';
import * as path from 'path';
import type { Canonical, CanonicalScreen, SkeletonResult } from './canonicalize';
import { planSemanticScreens, computeTabCluster } from './canonicalize';
import { tokenizeName, meaningfulTokens } from './semantic-names';
import { webPreviewRoute, webPreviewDir } from './agent-packet';
import { aliasSpecifierFor, loadWebApp, listWebSources, readHeader } from './passes/web-app';
import { webPipelineRootRel } from './passes/framework';

export type WebFramework = 'react' | 'next';

/** Marker on every write-locked file this module owns (safe to regenerate). */
export const WEB_SKELETON_MARKER = 'GENERATED SKELETON';
/** The build marker a screen/modal stub carries until the per-screen build replaces it. */
export const WEB_STUB_TODO = 'TODO(build)';

export interface WebSkeletonPreview {
  frameId: string;
  /** `/_preview/<frame>` — the exact route the verify harness screenshots. */
  route: string;
  kind: 'screen' | 'state' | 'modal';
  /** canonical screen (screen/state) or modal id the preview mounts. */
  targetId: string;
  /** file that registers it: the Next preview page, or App.tsx on react. */
  file: string;
}

export interface WebSkeletonResult extends SkeletonResult {
  framework: WebFramework;
  /** `.` / `src` (next) or `src` (react) — CONTRACTS §5. */
  pipelineRoot: string;
  previews: WebSkeletonPreview[];
  /** Folded modals → their presenter module + fixed presenter name. */
  modals: Array<{ modalId: string; baseCanonicalId: string | null; presenter: string; file: string; component: string }>;
  /** Contract files that already exist as hand-written code and were left untouched. */
  kept: string[];
  warnings: string[];
}

export interface WebSkeletonOptions {
  /** frameId → Figma frame name, used to name modal components (`LogOutModal`). */
  frameNames?: Record<string, string>;
}

// ── layout helpers ────────────────────────────────────────────────────────────

const isDir = (p: string): boolean => { try { return fsSync.statSync(p).isDirectory(); } catch { return false; } };

/** CONTRACTS §5 — where pipeline-owned web files live (shared with the asset
 *  pass's resources emitter, so the two can never disagree). */
export { webPipelineRootRel };

/** The theme module + stylesheet paths for a web framework (project-relative, POSIX).
 *  `importSpecifier` is how a screen imports the theme: on Next the tsconfig alias
 *  ONLY when the project's tsconfig/jsconfig maps one onto the theme module
 *  (create-next-app's default `@/*`), else the relative path from a screen page
 *  (`importFrom`) — `create-next-app --no-import-alias` has no `@/` and an unmapped
 *  `@/lib/theme/theme` is TS2307 (B12 fix round). */
export function webThemePaths(projectRoot: string, framework: string): { themeFile: string; cssFile: string; importSpecifier: string; importFrom: string } {
  if ((framework || '').toLowerCase() === 'next') {
    const pr = webPipelineRootRel(projectRoot, 'next');
    const base = pr === '.' ? 'lib/theme' : `${pr}/lib/theme`;
    const themeFile = `${base}/theme.ts`;
    const importFrom = `${pr === '.' ? 'app' : `${pr}/app`}/<route>/page.tsx`;
    const pageRel = importFrom.replace('<route>', 'route');
    const alias = aliasSpecifierFor(path.join(projectRoot, pageRel), path.join(projectRoot, themeFile));
    return { themeFile, cssFile: `${base}/theme.css`, importSpecifier: alias ?? importSpec(pageRel, themeFile), importFrom };
  }
  return { themeFile: 'src/theme/theme.ts', cssFile: 'src/theme/theme.css', importSpecifier: '../theme/theme', importFrom: 'src/screens/<Screen>.tsx' };
}

const posix = (p: string): string => p.split(path.sep).join('/');

/** Import specifier from one project-relative file to another (extension-less). */
function importSpec(fromRel: string, toRel: string, keepExt = false): string {
  let rel = posix(path.relative(path.dirname(fromRel), toRel));
  if (!keepExt) rel = rel.replace(/\.(tsx|ts|jsx|js)$/, '');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

// ── restart clean slate (PG-34) ───────────────────────────────────────────────

/** Markers of files the PIPELINE wrote (skeleton, design system, asset pass,
 *  verify preview entries). A file carrying one is regenerated by the rebuild. */
const PIPELINE_MARKERS = [
  WEB_SKELETON_MARKER,
  'GENERATED (extract-first design system)',
  'GENERATED by relay-server asset pass',
  '// GENERATED — device-framed preview entry',
  '// GENERATED — variant preview entry',
  '// GENERATED — app entrypoint',
];

export interface WebNukeResult {
  /** project-relative files removed. */
  removed: string[];
  /** project-relative directories left empty by the removal and pruned. */
  prunedDirs: string[];
  /** unmarked (hand-authored) files kept, which still import a removed file. */
  keptImporting: string[];
}

/**
 * The web half of a restart's clean slate (PG-34): remove the generated app surface
 * so the rebuild does not mix the previous build's screens, previews and routes
 * with the new ones — and NEVER a hand-authored file. The caller has committed a
 * git checkpoint first (the same data-safety contract as the flutter `lib/` nuke).
 *
 * Removed, across every source root the shared resolver walks (src/, app/,
 * components/, lib/, pages/):
 *   • every file carrying a `// canonicalId: <id> route: <route>` header — a
 *     generated screen, built or still the skeleton stub;
 *   • every file carrying a pipeline marker (`GENERATED SKELETON` router / route
 *     table / shell / modal stubs, the design-system theme, the asset pass's
 *     resources module, verify preview entries);
 *   • the verify preview routes: Next `<app>/%5Fpreview/**` (and a stray
 *     `<app>/_preview/**`), react `src/_preview/**`.
 * Kept: package.json, tsconfig, vite/next config, index.html, public/ (localized
 * assets are expensive and the asset pass re-emits the resources module), and any
 * unmarked file — reported in `keptImporting` when it imports something removed.
 */
async function listDirFiles(dir: string, acc: string[] = []): Promise<string[]> {
  let entries: fsSync.Dirent[] = [];
  try { entries = await fs.readdir(dir, { withFileTypes: true }); } catch { return acc; }
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) await listDirFiles(p, acc); else acc.push(p);
  }
  return acc;
}

export async function nukeWebAppSurface(projectRoot: string): Promise<WebNukeResult> {
  const out: WebNukeResult = { removed: [], prunedDirs: [], keptImporting: [] };
  const ix = await loadWebApp(projectRoot);
  if (!ix) return out;
  const rel = (p: string): string => posix(path.relative(projectRoot, p));
  const previewDirs = [
    ...(ix.appDir ? [path.join(ix.appDir, '%5Fpreview'), path.join(ix.appDir, '_preview')] : []),
    path.join(projectRoot, 'src', '_preview'),
  ];
  const inPreviewDir = (f: string): boolean => previewDirs.some((d) => f.startsWith(d + path.sep));
  // The resolver's walker never enters a preview dir (verify harness, not the app),
  // so the preview routes are removed wholesale.
  for (const d of previewDirs) {
    if (!isDir(d)) continue;
    const inside = await listDirFiles(d);
    await fs.rm(d, { recursive: true, force: true });
    out.removed.push(...inside.map(rel));
    out.prunedDirs.push(rel(d));
  }
  const files = await listWebSources(ix);
  const removed = new Set<string>();
  const kept: Array<{ file: string; src: string }> = [];
  for (const f of files) {
    const src = await fs.readFile(f, 'utf8').catch(() => '');
    const generated = inPreviewDir(f) || !!readHeader(src) || PIPELINE_MARKERS.some((m) => src.includes(m));
    if (!generated) { kept.push({ file: f, src }); continue; }
    await fs.rm(f, { force: true });
    removed.add(f);
    out.removed.push(rel(f));
  }
  // theme.css next to a removed theme module is part of the same generated pair.
  for (const f of files) {
    if (!removed.has(f) || !/theme\.ts$/.test(f)) continue;
    const css = f.replace(/\.ts$/, '.css');
    const cssSrc = await fs.readFile(css, 'utf8').catch(() => null);
    if (cssSrc != null && cssSrc.includes('GENERATED')) { await fs.rm(css, { force: true }); out.removed.push(rel(css)); }
  }
  // Prune directories the removal emptied (app/10-3/, app/%5Fpreview/10-3/ …), never a root.
  const roots = new Set(ix.sourceRoots.map((r) => path.resolve(r)));
  const dirs = [...new Set([...removed].map((f) => path.dirname(f)))].sort((a, b) => b.length - a.length);
  for (let d of dirs) {
    while (!roots.has(path.resolve(d)) && d.startsWith(projectRoot + path.sep)) {
      let entries: string[] = [];
      try { entries = await fs.readdir(d); } catch { break; }
      if (entries.length) break;
      await fs.rmdir(d).catch(() => undefined);
      out.prunedDirs.push(rel(d));
      d = path.dirname(d);
    }
  }
  // A kept (hand-authored) file that still imports a removed one is reported, not
  // touched: the rebuild's skeleton keeps it as hand-written, so a human must look.
  for (const k of kept) {
    const specs = [...k.src.matchAll(/from\s+['"](\.{1,2}\/[^'"]+)['"]/g)].map((m) => path.resolve(path.dirname(k.file), m[1]));
    if (specs.some((b) => ['', '.tsx', '.ts', '.jsx', '.js', '/index.tsx', '/index.ts'].some((ext) => removed.has(b + ext)))) out.keptImporting.push(rel(k.file));
  }
  return out;
}

/** A single-quoted TS string literal (the house style of the generated code). */
const lit = (s: string): string => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
/** A JSX attribute value: `"text"` when plain, `{'text'}` otherwise. */
const jsxAttr = (s: string): string => (/^[^"{}<>\\\n]*$/.test(s) ? `"${s}"` : `{${lit(s)}}`);

/** "loginScreen" → "Login", "283:1967" → "283:1967" (machine names stay recognisable). */
function humanTitle(name: string): string {
  const words = meaningfulTokens(name);
  if (!words.length) return tokenizeName(name).join(' ') || name;
  return words.map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

const pascalWords = (words: string[]): string =>
  words.map(w => (w ? w.charAt(0).toUpperCase() + w.slice(1) : w)).join('');

const idToken = (id: string): string => String(id).replace(/^[cm]_/, '').replace(/[^a-zA-Z0-9]+/g, '_').toLowerCase();

/** The fixed presenter name (must equal design-system.modalPresenterName). */
const presenterName = (modalId: string): string => `showModal_${idToken(modalId)}`;

// ── boilerplate detection (never clobber real code) ──────────────────────────

const ours = (src: string): boolean => src.includes(WEB_SKELETON_MARKER);

/** create-vite's react-ts App.tsx (the counter demo). */
const isViteAppBoilerplate = (src: string): boolean =>
  /count is/i.test(src) && /(vite|react)\.svg|Vite \+ React|Get started/i.test(src);
/** create-vite's main.tsx: render <App /> in StrictMode, nothing else. */
const isViteMainBoilerplate = (src: string): boolean =>
  /createRoot\(/.test(src) && /<App\s*\/>/.test(src) && !/Router|Provider|ModalHost/.test(src) && src.length < 800;
/** create-next-app's app/page.tsx and app/layout.tsx. */
const isNextPageBoilerplate = (src: string): boolean =>
  /page\.module\.css|Get started by editing|To get started, edit|next\.svg|vercel\.svg|Relay Next App/.test(src);
const isNextLayoutBoilerplate = (src: string): boolean =>
  /Create Next App|Generated by create next app|next\/font\/google/.test(src) && !/ModalHost/.test(src);

// ── the writer (additive, idempotent, reports what it did) ───────────────────

class Writer {
  files: string[] = [];
  kept: string[] = [];
  warnings: string[] = [];
  constructor(private root: string) {}
  abs(rel: string): string { return path.join(this.root, rel); }
  read(rel: string): string | null { try { return fsSync.readFileSync(this.abs(rel), 'utf8'); } catch { return null; } }
  exists(rel: string): boolean { return fsSync.existsSync(this.abs(rel)); }
  private async put(rel: string, content: string): Promise<void> {
    if (this.read(rel) === content) return;           // idempotent: no churn
    await fs.mkdir(path.dirname(this.abs(rel)), { recursive: true });
    await fs.writeFile(this.abs(rel), content, 'utf8');
    this.files.push(posix(rel));
  }
  /** A stub the build fills in: written only when absent (never clobber a built file). */
  async stub(rel: string, content: string): Promise<void> {
    if (this.exists(rel)) return;
    await this.put(rel, content);
  }
  /** A write-locked contract file: (re)generated when absent, ours, or `replaceable`
   *  boilerplate; a hand-written file is kept and reported. Returns true when the
   *  file on disk is now ours. */
  async locked(rel: string, content: string, replaceable?: (src: string) => boolean): Promise<boolean> {
    const cur = this.read(rel);
    if (cur === null || ours(cur) || (replaceable && replaceable(cur))) { await this.put(rel, content); return true; }
    this.kept.push(posix(rel));
    return false;
  }
}

// ── shared contract sources ───────────────────────────────────────────────────

const MODAL_CONTROLLER = `// ${WEB_SKELETON_MARKER} — modal controller (write-locked API surface).
// Folded modals are presented OVER their base screen, never routed to: a presenter
// \`showModal_<id>()\` calls modalController.open('<modalId>', <Content />) and the
// ModalHost mounted once at the app root renders it above a scrim.
// The controller REMEMBERS the open modal: a presenter called from a screen's (or the
// verify preview's) mount effect runs before the root ModalHost's own effect has
// subscribed, so a late subscriber must still receive what is already open.
import type { ReactNode } from 'react';

type Listener = (id: string | null, node: ReactNode | null) => void;
const listeners = new Set<Listener>();
let current: { id: string; node: ReactNode } | null = null;

export const modalController = {
  open(id: string, node: ReactNode): void {
    current = { id, node };
    listeners.forEach((l) => l(id, node));
  },
  close(): void {
    current = null;
    listeners.forEach((l) => l(null, null));
  },
  subscribe(l: Listener): () => void {
    listeners.add(l);
    if (current) l(current.id, current.node);
    return () => { listeners.delete(l); };
  },
};
`;

function modalHostSource(controllerSpec: string, client: boolean): string {
  return `${client ? "'use client';\n\n" : ''}// ${WEB_SKELETON_MARKER} — the ONE modal host, mounted once at the app root.
// Renders whatever modalController.open(…) presents above a scrim; a tap on the
// scrim closes it. The modal content positions itself (a bottom sheet anchors to
// bottom: 0, a dialog centers itself).
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { modalController } from '${controllerSpec}';

export function ModalHost() {
  const [node, setNode] = useState<ReactNode | null>(null);
  useEffect(() => modalController.subscribe((_id, next) => setNode(next)), []);
  if (!node) return null;
  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 1000 }}>
      <div
        aria-hidden="true"
        onClick={() => modalController.close()}
        style={{ position: 'absolute', inset: 0, background: 'rgba(0, 0, 0, 0.45)' }}
      />
      {node}
    </div>
  );
}
`;
}

const PLACEHOLDER = `// ${WEB_SKELETON_MARKER} — placeholder for a screen/modal slot the build has not implemented.
// A route that still renders this is NOT a built screen: finalize grades a flow
// edge to it \`missing\`. Every per-screen build replaces its slot's body.
export function PlaceholderScreen({ title, canonicalId, state, modal = false }: {
  title: string;
  canonicalId: string;
  state?: string;
  /** A modal slot: a sheet anchored to the bottom of the ModalHost layer. */
  modal?: boolean;
}) {
  const frame = modal
    ? { position: 'absolute', left: 0, right: 0, bottom: 0, minHeight: 240, background: '#ffffff', borderRadius: '16px 16px 0 0' } as const
    : { minHeight: '100vh' } as const;
  return (
    <div
      data-placeholder={canonicalId}
      style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8, ...frame }}
    >
      <strong>{title}</strong>
      <small>
        {canonicalId}
        {state && state !== 'default' ? \` · \${state}\` : ''} — not built yet
      </small>
    </div>
  );
}
`;

const SCREEN_STATE = `'use client';

// ${WEB_SKELETON_MARKER} — canonical screen STATE for Next pages.
// A Next page cannot take custom props, so a canonical screen reads its state from
// this context instead of a \`state\` prop: \`const state = useScreenState();\`. The
// verify preview route for a state wraps the page in <ScreenStateProvider state="…">.
import { createContext, useContext } from 'react';
import type { ReactNode } from 'react';

const ScreenStateContext = createContext<string>('default');

export function ScreenStateProvider({ state, children }: { state: string; children: ReactNode }) {
  return <ScreenStateContext.Provider value={state}>{children}</ScreenStateContext.Provider>;
}

export function useScreenState(): string {
  return useContext(ScreenStateContext);
}
`;

/** Theme stubs — the design-system phase (GEN_PHASE 4) overwrites them with the
 *  real tokens; they exist so the router/entry that imports them compiles first. */
const THEME_TS_STUB = `// ${WEB_SKELETON_MARKER} — theme/token stub. The design-system phase fills the real
// palette + type scale + spacing/radius before screen 1 builds.
export const AppTheme = {
  color: {},
  spacing: { s4: 4, s8: 8, s12: 12, s16: 16, s20: 20, s24: 24, s32: 32 },
  radius: { r8: 8, r12: 12, r16: 16, r24: 24 },
} as const;
`;
const THEME_CSS_STUB = `/* ${WEB_SKELETON_MARKER} — theme stylesheet stub (the design-system phase fills it). */
:root { color-scheme: light; }
body { margin: 0; }
`;

// ── route table ───────────────────────────────────────────────────────────────

interface PlannedScreen {
  c: CanonicalScreen;
  className: string;
  routeConst: string;
  route: string;
  title: string;
  states: string[];
  leadFrameId: string | null;
  tabIndex: number | null;
  /** project-relative screen file (react component file / next page). */
  file: string;
}

interface PlannedModal {
  modalId: string;
  frameId: string;
  baseCanonicalId: string | null;
  component: string;
  presenter: string;
  file: string;
  title: string;
}

function routesSource(screens: PlannedScreen[], entry: PlannedScreen | undefined): string {
  const lines = screens.map(s => `  ${s.routeConst}: ${lit(s.route)},`);
  return `// ${WEB_SKELETON_MARKER} — central route table (canonical routes; write-locked).
// Every navigation uses these constants (navigate(ROUTES.x) / router.push(ROUTES.x) /
// <Link to|href={ROUTES.x}>). Do NOT add, rename or remove routes here.
export const ROUTES = {
${lines.join('\n') || '  // (no routes)'}
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];

/** The app's entry screen (the flow graph's entry). */
export const ENTRY_ROUTE: AppRoute${screens.length ? '' : ' | string'} = ${entry ? `ROUTES.${entry.routeConst}` : lit('/')};
`;
}

// ── plan (shared by react + next) ─────────────────────────────────────────────

function planModals(canonical: Canonical, opts: WebSkeletonOptions | undefined, fileFor: (component: string) => string): PlannedModal[] {
  const used = new Set<string>();
  const out: PlannedModal[] = [];
  for (const c of canonical.screens) {
    for (const m of c.modals) {
      const frameName = opts?.frameNames?.[m.frameId] ?? '';
      const words = meaningfulTokens(frameName).filter(w => !/^(modal|sheet|dialog|popup|overlay)$/.test(w));
      let base = words.length ? `${pascalWords(words)}Modal` : `Modal${idToken(m.id).replace(/_/g, '')}`;
      if (!/^[A-Z]/.test(base)) base = `M${base}`;
      let name = base;
      for (let n = 2; used.has(name); n++) name = `${base}${n}`;
      used.add(name);
      out.push({
        modalId: m.id, frameId: m.frameId, baseCanonicalId: m.baseCanonicalId ?? c.canonicalId,
        component: name, presenter: presenterName(m.id), file: fileFor(name),
        title: frameName ? humanTitle(frameName) : m.id,
      });
    }
  }
  return out;
}

function stateType(s: PlannedScreen): string {
  return s.states.map(lit).join(' | ') || lit('default');
}

function screenHeader(s: PlannedScreen): string {
  const c = s.c;
  return `// canonicalId: ${c.canonicalId} route: ${s.route}
// ${WEB_SKELETON_MARKER} — write-locked route slot for canonical screen.
// states: ${s.states.join(', ') || 'default'}${c.modals.length ? `\n// modals: ${c.modals.map(m => m.id).join(', ')}` : ''}
// The per-screen build REPLACES the body of ${s.className} with the real UI (keep this header).
`;
}

// ── react ─────────────────────────────────────────────────────────────────────

const REACT_DEPS = { react: '^19.2.0', 'react-dom': '^19.2.0', 'react-router-dom': '^7.9.0' };
const REACT_DEV_DEPS = {
  '@types/react': '^19.2.0', '@types/react-dom': '^19.2.0', '@vitejs/plugin-react': '^6.1.0',
  typescript: '~6.0.2', vite: '^8.3.0',
};

async function reactToolchain(w: Writer, projectRoot: string): Promise<void> {
  const pkgRel = 'package.json';
  const cur = w.read(pkgRel);
  if (cur === null) {
    await w.stub(pkgRel, `${JSON.stringify({
      name: path.basename(projectRoot).toLowerCase().replace(/[^a-z0-9._-]+/g, '-') || 'app',
      private: true, version: '0.0.0', type: 'module',
      scripts: { dev: 'vite', build: 'tsc --noEmit -p tsconfig.json && vite build', preview: 'vite preview' },
      dependencies: REACT_DEPS, devDependencies: REACT_DEV_DEPS,
    }, null, 2)}\n`);
  } else {
    // An existing scaffold keeps its own versions; it only gains the router the
    // skeleton's App.tsx imports (`npm install` picks it up before the first build).
    try {
      const pkg = JSON.parse(cur) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
      const all = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
      if (!all['react-router-dom']) {
        pkg.dependencies = { ...(pkg.dependencies ?? {}), 'react-router-dom': REACT_DEPS['react-router-dom'] };
        await fs.writeFile(w.abs(pkgRel), `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
        w.files.push(pkgRel);
        w.warnings.push('added react-router-dom to package.json — run `npm install` before building');
      }
    } catch { w.warnings.push('package.json is not valid JSON — react-router-dom not added'); }
  }
  await w.stub('index.html', `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${path.basename(projectRoot).replace(/[<>&"]/g, '')}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`);
  if (!w.exists('vite.config.ts') && !w.exists('vite.config.js') && !w.exists('vite.config.mjs')) {
    // Previewed through the relay tunnel: Vite must accept the tunnel/platform hosts.
    await w.stub('vite.config.ts', `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

const allowedHosts = ['.trycloudflare.com', '.up.railway.app', 'localhost', '127.0.0.1'];

export default defineConfig({
  plugins: [react()],
  server: { host: true, allowedHosts },
  preview: { host: true, allowedHosts },
});
`);
  }
  if (!w.exists('tsconfig.json')) {
    await w.stub('tsconfig.json', `${JSON.stringify({
      compilerOptions: {
        target: 'ES2022', lib: ['ES2022', 'DOM', 'DOM.Iterable'], module: 'ESNext', moduleResolution: 'bundler',
        types: ['vite/client'], jsx: 'react-jsx', strict: true, noEmit: true, skipLibCheck: true,
        verbatimModuleSyntax: true, noUnusedLocals: true, noUnusedParameters: true, noFallthroughCasesInSwitch: true,
      },
      include: ['src'],
    }, null, 2)}\n`);
  }
}

async function generateReact(projectRoot: string, canonical: Canonical, opts?: WebSkeletonOptions): Promise<WebSkeletonResult> {
  const w = new Writer(projectRoot);
  await reactToolchain(w, projectRoot);

  const semantics = planSemanticScreens(canonical);       // rewrites c.route → semantic path
  const tab = computeTabCluster(canonical);
  const planned: PlannedScreen[] = canonical.screens.map(c => {
    const sem = semantics.get(c.canonicalId)!;
    return {
      c, className: sem.className, routeConst: sem.routeConst, route: c.route, title: humanTitle(c.name),
      states: c.states.map(s => s.id), leadFrameId: c.states[0]?.frameId ?? c.frameIds[0] ?? null,
      tabIndex: tab ? (tab.memberIds.indexOf(c.canonicalId) >= 0 ? tab.memberIds.indexOf(c.canonicalId) : null) : null,
      file: `src/screens/${sem.className}.tsx`,
    };
  });
  const entry = planned.find(s => s.c.canonicalId === canonical.flow?.entryCanonicalId) ?? planned[0];
  const modals = planModals(canonical, opts, name => `src/modal/${name}.tsx`);

  // Contract infrastructure.
  await w.locked('src/router/routes.ts', routesSource(planned, entry));
  await w.stub('src/theme/theme.ts', THEME_TS_STUB);
  await w.stub('src/theme/theme.css', THEME_CSS_STUB);
  await w.locked('src/components/PlaceholderScreen.tsx', PLACEHOLDER);
  await w.locked('src/modal/modalController.ts', MODAL_CONTROLLER);
  await w.locked('src/modal/ModalHost.tsx', modalHostSource('./modalController', false));

  // Per-screen stubs (never clobber a built screen).
  for (const s of planned) {
    await w.stub(s.file, `${screenHeader(s)}import { PlaceholderScreen } from '../components/PlaceholderScreen';

export type ${s.className}State = ${stateType(s)};

export function ${s.className}({ state = ${lit(s.states[0] ?? 'default')} }: { state?: ${s.className}State }) {
  // ${WEB_STUB_TODO}: implement this screen against its reference. Each state is
  // verified individually via <${s.className} state="<id>" /> at its /_preview route.
  return <PlaceholderScreen title=${jsxAttr(s.title)} canonicalId=${jsxAttr(s.c.canonicalId)} state={state} />;
}
`);
  }
  // Folded-modal presenter stubs (fixed names — the verify harness calls them).
  for (const m of modals) {
    await w.stub(m.file, modalStubSource(m, './modalController', '../components/PlaceholderScreen', false));
  }

  // Tab shell.
  const tabMembers = tab ? tab.memberIds.map(id => planned.find(p => p.c.canonicalId === id)!).filter(Boolean) : [];
  if (tabMembers.length) {
    await w.locked('src/shell/AppShell.tsx', `// ${WEB_SKELETON_MARKER} — write-locked APP SHELL (tab cluster host).
// The tab screens render inside <Outlet /> behind ONE shared tab bar. A hosted screen
// must NOT render its own bottom navigation and must never navigate() to a sibling
// tab — switching tabs is this shell's job.
// tabCluster: ${tabMembers.map(m => m.c.canonicalId).join(', ')}
import { NavLink, Outlet } from 'react-router-dom';
import { ROUTES } from '../router/routes';

const TABS = [
${tabMembers.map(m => `  { to: ROUTES.${m.routeConst}, label: ${lit(m.title)} },`).join('\n')}
] as const;

export function AppShell() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <div style={{ flex: 1 }}>
        <Outlet />
      </div>
      <nav style={{ display: 'flex', justifyContent: 'space-around', position: 'sticky', bottom: 0 }}>
        {TABS.map((t) => (
          <NavLink key={t.to} to={t.to}>
            {t.label}
          </NavLink>
        ))}
      </nav>
    </div>
  );
}
`);
  }

  // Modal verify harness components (src/_preview is never shipped UI).
  const previews: WebSkeletonPreview[] = [];
  const previewImports: string[] = [];
  for (const m of modals) {
    const base = planned.find(p => p.c.canonicalId === m.baseCanonicalId);
    if (!base) { w.warnings.push(`modal ${m.modalId}: base ${m.baseCanonicalId} is not a canonical screen — no preview route`); continue; }
    const comp = `${m.component}Preview`;
    const rel = `src/_preview/${comp}.tsx`;
    await w.locked(rel, `// ${WEB_SKELETON_MARKER} — verify preview: base screen ${base.c.canonicalId} with modal ${m.modalId} presented.
// Route ${webPreviewRoute(m.frameId)} (pipeline-owned; finalize hygiene strips it). The base
// screen's own preview route renders with NO modal open.
import { useEffect } from 'react';
import { ${base.className} } from '${importSpec(rel, base.file)}';
import { ${m.presenter} } from '${importSpec(rel, m.file)}';

export function ${comp}() {
  useEffect(() => {
    ${m.presenter}();
  }, []);
  return <${base.className} />;
}
`);
    previewImports.push(`import { ${comp} } from './_preview/${comp}';`);
    previews.push({ frameId: m.frameId, route: webPreviewRoute(m.frameId), kind: 'modal', targetId: m.modalId, file: 'src/App.tsx' });
  }

  // Router — ONE <Route> per line (finalize hygiene strips preview routes line-wise).
  const routeLines: string[] = [];
  for (const s of planned.filter(p => p.tabIndex === null)) {
    routeLines.push(`        <Route path={ROUTES.${s.routeConst}} element={<${s.className} />} />`);
  }
  if (tabMembers.length) {
    routeLines.push(`        <Route element={<AppShell />}>`);
    for (const s of tabMembers) routeLines.push(`          <Route path={ROUTES.${s.routeConst}} element={<${s.className} />} />`);
    routeLines.push(`        </Route>`);
  }
  const previewLines: string[] = [];
  for (const s of planned) {
    if (s.leadFrameId) {
      previewLines.push(`        <Route path=${jsxAttr(webPreviewRoute(s.leadFrameId))} element={<${s.className} />} />`);
      previews.push({ frameId: s.leadFrameId, route: webPreviewRoute(s.leadFrameId), kind: 'screen', targetId: s.c.canonicalId, file: 'src/App.tsx' });
    }
    for (const st of s.c.states) {
      if (st.frameId === s.leadFrameId) continue;
      previewLines.push(`        <Route path=${jsxAttr(webPreviewRoute(st.frameId))} element={<${s.className} state=${jsxAttr(st.id)} />} />`);
      previews.push({ frameId: st.frameId, route: webPreviewRoute(st.frameId), kind: 'state', targetId: s.c.canonicalId, file: 'src/App.tsx' });
    }
  }
  for (const m of modals) {
    if (!planned.some(p => p.c.canonicalId === m.baseCanonicalId)) continue;
    previewLines.push(`        <Route path=${jsxAttr(webPreviewRoute(m.frameId))} element={<${m.component}Preview />} />`);
  }

  // main.tsx owns the router when it already wraps one; otherwise App does.
  const mainCur = w.read('src/main.tsx');
  const mainIsOurs = mainCur === null || ours(mainCur) || isViteMainBoilerplate(mainCur);
  const routerInApp = mainIsOurs || !/BrowserRouter|HashRouter|MemoryRouter|RouterProvider/.test(mainCur ?? '');
  const rrImports = [...(routerInApp ? ['BrowserRouter'] : []), 'Navigate', 'Route', 'Routes'];
  const screenImports = planned.map(s => `import { ${s.className} } from '${importSpec('src/App.tsx', s.file)}';`);
  const app = `// ${WEB_SKELETON_MARKER} — central router (every canonical route registered; write-locked).
// Per-screen builds fill the screen components in src/screens/, NOT this table.
// /_preview/<frame> routes are the verify harness (pipeline-owned; finalize strips them).
import { ${rrImports.join(', ')} } from 'react-router-dom';
import { ENTRY_ROUTE, ROUTES } from './router/routes';
import { ModalHost } from './modal/ModalHost';
${tabMembers.length ? `import { AppShell } from './shell/AppShell';\n` : ''}${screenImports.join('\n')}
${previewImports.join('\n')}${previewImports.length ? '\n' : ''}
export default function App() {
  return (
    ${routerInApp ? '<BrowserRouter>' : '<>'}
      <Routes>
${routeLines.join('\n')}
${previewLines.join('\n')}
        <Route path="*" element={<Navigate to={ENTRY_ROUTE} replace />} />
      </Routes>
      <ModalHost />
    ${routerInApp ? '</BrowserRouter>' : '</>'}
  );
}
`;
  const appOk = await w.locked('src/App.tsx', app, isViteAppBoilerplate);
  if (!appOk) w.warnings.push('src/App.tsx is hand-written — the canonical <Routes> table was NOT generated; the router must register every ROUTES entry + /_preview route itself');
  await w.locked('src/main.tsx', `// ${WEB_SKELETON_MARKER} — app entry (theme stylesheet + router app).
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './theme/theme.css';
import App from './App';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`, isViteMainBoilerplate);

  return {
    framework: 'react', pipelineRoot: 'src',
    files: w.files, kept: w.kept, warnings: w.warnings, previews,
    routes: planned.map(s => ({ canonicalId: s.c.canonicalId, route: s.route, className: s.className, routeConst: s.routeConst, file: s.file })),
    modals: modals.map(m => ({ modalId: m.modalId, baseCanonicalId: m.baseCanonicalId, presenter: m.presenter, file: m.file, component: m.component })),
    ...(tab ? { tabCluster: tab } : {}),
  };
}

function modalStubSource(m: PlannedModal, controllerSpec: string, placeholderSpec: string, client: boolean): string {
  return `${client ? "'use client';\n\n" : ''}// ${WEB_SKELETON_MARKER} — modal presenter slot for folded modal ${m.modalId} (frame ${m.frameId}).
// base: ${m.baseCanonicalId ?? '(unbound)'}
// The presenter NAME ${m.presenter}() is FIXED: the base screen calls it from the
// trigger that opens this modal, and the verify harness calls it verbatim. The build
// REPLACES the body of ${m.component} with the real modal UI.
import { modalController } from '${controllerSpec}';
import { PlaceholderScreen } from '${placeholderSpec}';

export function ${m.component}() {
  // ${WEB_STUB_TODO}: implement this modal against its reference.
  return <PlaceholderScreen title=${jsxAttr(m.title)} canonicalId=${jsxAttr(m.modalId)} modal />;
}

/** Presents ${m.modalId} over its base screen. */
export function ${m.presenter}(): void {
  modalController.open(${lit(m.modalId)}, <${m.component} />);
}
`;
}

// ── next ──────────────────────────────────────────────────────────────────────

const NEXT_DEPS = { next: '^16.0.0', react: '^19.2.0', 'react-dom': '^19.2.0' };
const NEXT_DEV_DEPS = { typescript: '^5', '@types/node': '^20', '@types/react': '^19', '@types/react-dom': '^19' };

/** Insert `output: 'export'` (+ unoptimized images) into a create-next-app config. */
function withStaticExport(src: string): string | null {
  if (/\boutput\s*:/.test(src)) return src;
  const m = /(const\s+nextConfig\s*(?::\s*NextConfig)?\s*=\s*\{)/.exec(src)
    ?? /(module\.exports\s*=\s*\{)/.exec(src)
    ?? /(export\s+default\s*\{)/.exec(src);
  if (!m) return null;
  const images = /\bimages\s*:/.test(src) ? '' : `\n  images: { unoptimized: true },`;
  return `${src.slice(0, m.index + m[0].length)}\n  // Verify serves a static export (/_preview/<frame> → out/_preview/<frame>.html).\n  output: 'export',${images}${src.slice(m.index + m[0].length)}`;
}

async function nextToolchain(w: Writer, projectRoot: string): Promise<void> {
  if (!w.exists('package.json')) {
    await w.stub('package.json', `${JSON.stringify({
      name: path.basename(projectRoot).toLowerCase().replace(/[^a-z0-9._-]+/g, '-') || 'app',
      private: true, version: '0.1.0',
      scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
      dependencies: NEXT_DEPS, devDependencies: NEXT_DEV_DEPS,
    }, null, 2)}\n`);
  }
  if (!w.exists('tsconfig.json')) {
    const pr = webPipelineRootRel(projectRoot, 'next');
    await w.stub('tsconfig.json', `${JSON.stringify({
      compilerOptions: {
        target: 'ES2017', lib: ['dom', 'dom.iterable', 'esnext'], allowJs: true, skipLibCheck: true, strict: true,
        noEmit: true, esModuleInterop: true, module: 'esnext', moduleResolution: 'bundler', resolveJsonModule: true,
        isolatedModules: true, jsx: 'react-jsx', incremental: true, plugins: [{ name: 'next' }],
        paths: { '@/*': [pr === '.' ? './*' : `./${pr}/*`] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts', '.next/dev/types/**/*.ts', '**/*.mts'],
      exclude: ['node_modules'],
    }, null, 2)}\n`);
  }
  const cfg = ['next.config.ts', 'next.config.mjs', 'next.config.js'].find(f => w.exists(f));
  if (!cfg) {
    await w.stub('next.config.mjs', `/** @type {import('next').NextConfig} */
const nextConfig = {
  // Verify serves a static export (/_preview/<frame> → out/_preview/<frame>.html).
  output: 'export',
  images: { unoptimized: true },
};

export default nextConfig;
`);
  } else {
    const cur = w.read(cfg) ?? '';
    const next = withStaticExport(cur);
    if (next === null) w.warnings.push(`${cfg}: could not add output: 'export' (unrecognised shape) — the verify harness needs a static export`);
    else if (next !== cur) { await fs.writeFile(w.abs(cfg), next, 'utf8'); w.files.push(cfg); }
  }
}

async function generateNext(projectRoot: string, canonical: Canonical, opts?: WebSkeletonOptions): Promise<WebSkeletonResult> {
  const w = new Writer(projectRoot);
  await nextToolchain(w, projectRoot);
  const pr = webPipelineRootRel(projectRoot, 'next');
  const at = (rel: string): string => (pr === '.' ? rel : `${pr}/${rel}`);
  const appDir = at('app');

  const semantics = planSemanticScreens(canonical);
  const tab = computeTabCluster(canonical);
  const planned: PlannedScreen[] = canonical.screens.map(c => {
    const sem = semantics.get(c.canonicalId)!;
    const tabIndex = tab && tab.memberIds.includes(c.canonicalId) ? tab.memberIds.indexOf(c.canonicalId) : null;
    const segs = c.route.replace(/^\/+/, '');
    return {
      c, className: sem.className, routeConst: sem.routeConst, route: c.route, title: humanTitle(c.name),
      states: c.states.map(s => s.id), leadFrameId: c.states[0]?.frameId ?? c.frameIds[0] ?? null, tabIndex,
      file: `${appDir}/${tabIndex !== null ? '(tabs)/' : ''}${segs}/page.tsx`,
    };
  });
  const entry = planned.find(s => s.c.canonicalId === canonical.flow?.entryCanonicalId) ?? planned[0];
  const modals = planModals(canonical, opts, name => at(`components/modals/${name}.tsx`));

  const routesRel = at('lib/routes.ts');
  const controllerRel = at('lib/modal/modalController.ts');
  const placeholderRel = at('components/PlaceholderScreen.tsx');
  const hostRel = at('components/ModalHost.tsx');
  const stateRel = at('components/screenState.tsx');
  const shellRel = at('components/AppShell.tsx');
  const themeCss = at('lib/theme/theme.css');

  await w.locked(routesRel, routesSource(planned, entry));
  await w.stub(at('lib/theme/theme.ts'), THEME_TS_STUB);
  await w.stub(themeCss, THEME_CSS_STUB);
  await w.locked(placeholderRel, PLACEHOLDER);
  await w.locked(controllerRel, MODAL_CONTROLLER);
  await w.locked(hostRel, modalHostSource(importSpec(hostRel, controllerRel), true));
  await w.locked(stateRel, SCREEN_STATE);

  // Per-screen stub pages: the header sits ABOVE 'use client' (comments may precede
  // a directive). A page cannot take custom props, so state comes from context.
  for (const s of planned) {
    const multi = s.states.length > 1;
    await w.stub(s.file, `${screenHeader(s)}'use client';

import { PlaceholderScreen } from '${importSpec(s.file, placeholderRel)}';
${multi ? `import { useScreenState } from '${importSpec(s.file, stateRel)}';\n` : ''}
export default function ${s.className}() {
${multi ? `  // One of: ${s.states.map(lit).join(', ')} — each state is verified at its own /_preview route.\n  const state = useScreenState();\n` : ''}  // ${WEB_STUB_TODO}: implement this screen against its reference.
  return <PlaceholderScreen title=${jsxAttr(s.title)} canonicalId=${jsxAttr(s.c.canonicalId)}${multi ? ' state={state}' : ''} />;
}
`);
  }
  for (const m of modals) {
    await w.stub(m.file, modalStubSource(m, importSpec(m.file, controllerRel), importSpec(m.file, placeholderRel), false));
  }

  // Tab cluster: the `(tabs)` route group's layout hosts the ONE shared tab bar.
  const tabMembers = tab ? tab.memberIds.map(id => planned.find(p => p.c.canonicalId === id)!).filter(Boolean) : [];
  if (tabMembers.length) {
    await w.locked(shellRel, `'use client';

// ${WEB_SKELETON_MARKER} — write-locked APP SHELL (tab cluster host).
// Rendered by app/(tabs)/layout.tsx around every tab page, behind ONE shared tab bar.
// A hosted page must NOT render its own bottom navigation and must never
// router.push() a sibling tab — switching tabs is this shell's job.
// tabCluster: ${tabMembers.map(m => m.c.canonicalId).join(', ')}
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import type { ReactNode } from 'react';
import { ROUTES } from '${importSpec(shellRel, routesRel)}';

const TABS = [
${tabMembers.map(m => `  { href: ROUTES.${m.routeConst}, label: ${lit(m.title)} },`).join('\n')}
] as const;

export function AppShell({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <div style={{ flex: 1 }}>{children}</div>
      <nav style={{ display: 'flex', justifyContent: 'space-around', position: 'sticky', bottom: 0 }}>
        {TABS.map((t) => (
          <Link key={t.href} href={t.href} aria-current={pathname === t.href ? 'page' : undefined}>
            {t.label}
          </Link>
        ))}
      </nav>
    </div>
  );
}
`);
    const tabsLayout = `${appDir}/(tabs)/layout.tsx`;
    await w.locked(tabsLayout, `// ${WEB_SKELETON_MARKER} — tab cluster layout (route group; adds no URL segment).
import type { ReactNode } from 'react';
import { AppShell } from '${importSpec(tabsLayout, shellRel)}';

export default function TabsLayout({ children }: { children: ReactNode }) {
  return <AppShell>{children}</AppShell>;
}
`);
  }

  // Root layout (theme + the one ModalHost) and the entry redirect.
  const layoutRel = `${appDir}/layout.tsx`;
  // A scaffold's own global stylesheet (create-next-app's app/globals.css — Tailwind's
  // entry when the app uses it) stays imported; the theme stylesheet comes after it so
  // the design tokens win.
  const globalsCss = w.exists(`${appDir}/globals.css`) ? `import './globals.css';\n` : '';
  const layoutOk = await w.locked(layoutRel, `// ${WEB_SKELETON_MARKER} — root layout: the theme stylesheet + the ONE modal host.
import type { ReactNode } from 'react';
${globalsCss}import '${importSpec(layoutRel, themeCss, true)}';
import { ModalHost } from '${importSpec(layoutRel, hostRel)}';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        <ModalHost />
      </body>
    </html>
  );
}
`, isNextLayoutBoilerplate);
  if (!layoutOk) w.warnings.push(`${layoutRel} is hand-written — it must import ${themeCss} and render <ModalHost /> once, or folded modals never appear`);
  const indexRel = `${appDir}/page.tsx`;
  await w.locked(indexRel, `// ${WEB_SKELETON_MARKER} — \`/\` redirects to the entry screen.
import { redirect } from 'next/navigation';
import { ENTRY_ROUTE } from '${importSpec(indexRel, routesRel)}';

export default function Index() {
  redirect(ENTRY_ROUTE);
}
`, isNextPageBoilerplate);

  // Verify preview routes: app/%5Fpreview/<frame>/page.tsx → /_preview/<frame>.
  const previews: WebSkeletonPreview[] = [];
  const previewRel = (frameId: string): string => `${appDir}/${webPreviewDir(frameId)}/page.tsx`;
  const previewHead = (route: string, what: string): string =>
    `// ${WEB_SKELETON_MARKER} — verify preview ${route}: ${what}.
// Pipeline-owned (the folder is %5Fpreview because a \`_preview\` folder is PRIVATE in
// the App Router and never routed); finalize hygiene strips it from the deliverable.
`;
  const fnName = (frameId: string): string => `Preview_${frameId.replace(/[^a-zA-Z0-9]+/g, '_')}`;
  for (const s of planned) {
    if (s.leadFrameId) {
      const rel = previewRel(s.leadFrameId);
      const route = webPreviewRoute(s.leadFrameId);
      await w.locked(rel, `${previewHead(route, `screen ${s.c.canonicalId}`)}import ${s.className} from '${importSpec(rel, s.file)}';

export default function ${fnName(s.leadFrameId)}() {
  return <${s.className} />;
}
`);
      previews.push({ frameId: s.leadFrameId, route, kind: 'screen', targetId: s.c.canonicalId, file: rel });
    }
    for (const st of s.c.states) {
      if (st.frameId === s.leadFrameId) continue;
      const rel = previewRel(st.frameId);
      const route = webPreviewRoute(st.frameId);
      await w.locked(rel, `${previewHead(route, `screen ${s.c.canonicalId} in state '${st.id}'`)}import ${s.className} from '${importSpec(rel, s.file)}';
import { ScreenStateProvider } from '${importSpec(rel, stateRel)}';

export default function ${fnName(st.frameId)}() {
  return (
    <ScreenStateProvider state=${jsxAttr(st.id)}>
      <${s.className} />
    </ScreenStateProvider>
  );
}
`);
      previews.push({ frameId: st.frameId, route, kind: 'state', targetId: s.c.canonicalId, file: rel });
    }
  }
  for (const m of modals) {
    const base = planned.find(p => p.c.canonicalId === m.baseCanonicalId);
    if (!base) { w.warnings.push(`modal ${m.modalId}: base ${m.baseCanonicalId} is not a canonical screen — no preview route`); continue; }
    const rel = previewRel(m.frameId);
    const route = webPreviewRoute(m.frameId);
    await w.locked(rel, `'use client';

${previewHead(route, `base ${base.c.canonicalId} with modal ${m.modalId} presented (the base's own preview renders it closed)`)}import { useEffect } from 'react';
import ${base.className} from '${importSpec(rel, base.file)}';
import { ${m.presenter} } from '${importSpec(rel, m.file)}';

export default function ${fnName(m.frameId)}() {
  useEffect(() => {
    ${m.presenter}();
  }, []);
  return <${base.className} />;
}
`);
    previews.push({ frameId: m.frameId, route, kind: 'modal', targetId: m.modalId, file: rel });
  }
  if (!w.exists('next-env.d.ts')) {
    await w.stub('next-env.d.ts', `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`);
  }

  return {
    framework: 'next', pipelineRoot: pr,
    files: w.files, kept: w.kept, warnings: w.warnings, previews,
    routes: planned.map(s => ({ canonicalId: s.c.canonicalId, route: s.route, className: s.className, routeConst: s.routeConst, file: s.file })),
    modals: modals.map(m => ({ modalId: m.modalId, baseCanonicalId: m.baseCanonicalId, presenter: m.presenter, file: m.file, component: m.component })),
    ...(tab ? { tabCluster: tab } : {}),
  };
}

// ── the slot contract, for the per-screen packet (buildCanonicalContext) ──────

export interface WebScreenSlot {
  className: string;
  routeConst: string;
  route: string;
  /** react: `src/screens/<Class>.tsx`; next: `app/[(tabs)/]<route>/page.tsx` —
   *  relative to the pipeline root (CONTRACTS §5; `.` or `src` on next). */
  file: string;
  tab: boolean;
}

/** Where the web skeleton put (or will put) a canonical screen's slot. Pure — call
 *  after planSemanticScreens has made the routes semantic (the skeleton does). */
export function webScreenSlot(canonical: Canonical, canonicalId: string, framework: string): WebScreenSlot | null {
  const sem = planSemanticScreens(canonical).get(canonicalId);
  const c = canonical.screens.find(x => x.canonicalId === canonicalId);
  if (!sem || !c) return null;
  const tab = !!computeTabCluster(canonical)?.memberIds.includes(canonicalId);
  const file = (framework || '').toLowerCase() === 'next'
    ? `app/${tab ? '(tabs)/' : ''}${c.route.replace(/^\/+/, '')}/page.tsx`
    : `src/screens/${sem.className}.tsx`;
  return { className: sem.className, routeConst: sem.routeConst, route: c.route, file, tab };
}

/** The presenter slot of every folded modal: modalId → component, fixed presenter
 *  name and file (pipeline-root relative), exactly as the skeleton names them. */
export function webModalSlots(canonical: Canonical, framework: string, frameNames?: Record<string, string>): Map<string, { component: string; presenter: string; file: string }> {
  const next = (framework || '').toLowerCase() === 'next';
  const out = new Map<string, { component: string; presenter: string; file: string }>();
  for (const m of planModals(canonical, { frameNames }, name => (next ? `components/modals/${name}.tsx` : `src/modal/${name}.tsx`))) {
    out.set(m.modalId, { component: m.component, presenter: m.presenter, file: m.file });
  }
  return out;
}

/**
 * Generate the deterministic web skeleton for a canonical app (react or next).
 * Like generateFlutterSkeleton it REWRITES canonical.screens[].route to the semantic
 * path (planSemanticScreens), so the caller must persist the canonical afterwards.
 */
export async function generateWebSkeleton(
  projectRoot: string, canonical: Canonical, framework: string, opts?: WebSkeletonOptions,
): Promise<WebSkeletonResult> {
  const fw = (framework || '').toLowerCase();
  if (fw === 'next') return generateNext(projectRoot, canonical, opts);
  if (fw === 'react') return generateReact(projectRoot, canonical, opts);
  throw new Error(`generateWebSkeleton: '${framework}' is not a web framework (react | next)`);
}

/** A screen/modal file that is still the skeleton's stub (not built) — the shared
 *  resolver's definition, so the skeleton and every pass agree. */
export { isSkeletonStub as isWebSkeletonStub } from './passes/web-app';
