// GENERATED from the Flutter SDK (Flutter 3.47.5, packages/flutter/lib/src/{material,widgets,cupertino,painting,animation}):
// every public top-level class / enum / mixin / typedef name. A shared component the
// pipeline names must never shadow one of these (an app `BackButton` makes every
// `import 'package:flutter/material.dart'` ambiguous).
// Regenerate: grep -rhoE '^(abstract |final |base |sealed |interface |mixin )*(class|enum|mixin|typedef) [A-Z][A-Za-z0-9]*' \
//   material widgets cupertino painting animation | awk '{print $NF}' | sort -u
const FLUTTER_SDK_NAME_LIST = `
AboutDialog AboutListTile AbsorbPointer AbstractLayoutBuilder AccessibilityEvaluation Accumulator
Action ActionChip ActionDispatcher ActionIconTheme ActionIconThemeData ActionListener
ActionListenerCallback Actions ActivateAction ActivateIntent Adaptation
AdaptiveTextSelectionToolbar AlertDialog Align AlignTransition Alignment AlignmentDirectional
AlignmentGeometry AlwaysScrollableScrollPhysics AlwaysStoppedAnimation AndroidOverscrollIndicator
AndroidView AndroidViewSurface Animatable AnimatableCallback AnimatedAlign AnimatedBuilder
AnimatedContainer AnimatedCrossFade AnimatedCrossFadeBuilder AnimatedDefaultTextStyle
AnimatedFractionallySizedBox AnimatedGrid AnimatedGridState AnimatedIcon AnimatedIconData
AnimatedIcons AnimatedItemBuilder AnimatedList AnimatedListState AnimatedModalBarrier
AnimatedOpacity AnimatedPadding AnimatedPhysicalModel AnimatedPositioned
AnimatedPositionedDirectional AnimatedRemovedItemBuilder AnimatedRotation AnimatedScale
AnimatedSize AnimatedSlide AnimatedSwitcher AnimatedSwitcherLayoutBuilder
AnimatedSwitcherTransitionBuilder AnimatedTheme AnimatedTransitionBuilder AnimatedWidget
AnimatedWidgetBaseState Animation AnimationBehavior AnimationController AnimationEagerListenerMixin
AnimationLazyListenerMixin AnimationLocalListenersMixin AnimationLocalStatusListenersMixin
AnimationMax AnimationMean AnimationMin AnimationStatus AnimationStatusListener AnimationStyle
AnimationWithParentMixin AnnotatedRegion AppBar AppBarTheme AppBarThemeData AppExitRequestCallback
AppKitView AppLifecycleListener AppPrivateCommandCallback AspectRatio AssetBundleImageKey
AssetBundleImageProvider AssetImage AsyncSnapshot AsyncWidgetBuilder Autocomplete
AutocompleteFieldViewBuilder AutocompleteFirstOptionIntent AutocompleteHighlightedOption
AutocompleteLastOptionIntent AutocompleteNextOptionIntent AutocompleteNextPageOptionIntent
AutocompleteOnSelected AutocompleteOptionToString AutocompleteOptionsBuilder
AutocompleteOptionsViewBuilder AutocompletePreviousOptionIntent
AutocompletePreviousPageOptionIntent AutofillContextAction AutofillGroup AutofillGroupState
AutomaticKeepAlive AutomaticKeepAliveClientMixin AutomaticNotchedShape AutovalidateMode Axis
AxisDirection BackButton BackButtonDispatcher BackButtonIcon BackButtonListener BackdropFilter
BackdropGroup Badge BadgeTheme BadgeThemeData BallisticScrollActivity Banner BannerLocation
BannerPainter BaseRangeSliderTrackShape BaseSliderTrackShape BaseWindowController Baseline
BeveledRectangleBorder BlockSemantics Border BorderDirectional BorderRadius BorderRadiusDirectional
BorderRadiusGeometry BorderRadiusTween BorderSide BorderStyle BorderTween BottomAppBar
BottomAppBarTheme BottomAppBarThemeData BottomNavigationBar BottomNavigationBarItem
BottomNavigationBarLandscapeLayout BottomNavigationBarTheme BottomNavigationBarThemeData
BottomNavigationBarType BottomSheet BottomSheetDragEndHandler BottomSheetDragStartHandler
BottomSheetThemeData BouncingScrollPhysics BouncingScrollSimulation BoxBorder BoxConstraintsTween
BoxDecoration BoxFit BoxPainter BoxScrollView BoxShadow BoxShape BuildContext BuildOwner BuildScope
Builder ButtonActivateIntent ButtonBar ButtonBarLayoutBehavior ButtonBarTheme ButtonBarThemeData
ButtonLayerBuilder ButtonSegment ButtonStyle ButtonStyleButton ButtonTextTheme ButtonTheme
ButtonThemeData CalendarDatePicker CalendarDelegate CallbackAction CallbackShortcuts CapturedThemes
Card CardTheme CardThemeData CarouselController CarouselScrollPhysics CarouselView
CarouselViewTheme CarouselViewThemeData CatmullRomCurve CatmullRomSpline Center
ChangeReportingBehavior CharacterActivator Checkbox CheckboxListTile CheckboxMenuButton
CheckboxTheme CheckboxThemeData CheckedModeBanner CheckedPopupMenuItem CheckmarkableChipAttributes
ChildBackButtonDispatcher ChildIndexGetter ChildVicinity Chip ChipAnimationStyle ChipAttributes
ChipTheme ChipThemeData ChoiceChip CircleAvatar CircleBorder CircularNotchedRectangle
CircularProgressIndicator ClampingScrollPhysics ClampingScrollSimulation ClipContext ClipOval
ClipPath ClipRRect ClipRSuperellipse ClipRect ClipboardStatus ClipboardStatusNotifier CloseButton
CloseButtonIcon CollapseMode ColorFiltered ColorProperty ColorScheme ColorSwatch ColorTween
ColoredBox Colors Column ComponentElement CompositedTransformFollower CompositedTransformTarget
CompoundAnimation ConditionalElementVisitor ConfirmDismissCallback ConnectionState ConstantTween
ConstrainedBox ConstrainedLayoutBuilder ConstraintsTransformBox Container
ContentInsertionConfiguration ContextAction ContextMenuButtonItem ContextMenuButtonType
ContextMenuController ContinuousRectangleBorder ControlsDetails ControlsWidgetBuilder
CopySelectionTextIntent CreatePlatformViewCallback CreateRectTween CrossFadeState Cubic
CupertinoActionSheet CupertinoActionSheetAction CupertinoActivityIndicator
CupertinoAdaptiveTextSelectionToolbar CupertinoAlertDialog CupertinoApp
CupertinoBasedMaterialThemeData CupertinoButton CupertinoButtonSize CupertinoCheckbox
CupertinoColors CupertinoContextMenu CupertinoContextMenuAction CupertinoContextMenuBuilder
CupertinoDatePicker CupertinoDatePickerMode CupertinoDesktopTextSelectionControls
CupertinoDesktopTextSelectionToolbar CupertinoDesktopTextSelectionToolbarButton
CupertinoDialogAction CupertinoDialogRoute CupertinoDynamicColor CupertinoExpansionTile
CupertinoFocusHalo CupertinoFormRow CupertinoFormSection CupertinoFullscreenDialogTransition
CupertinoIconThemeData CupertinoIcons CupertinoLinearActivityIndicator CupertinoListSection
CupertinoListSectionType CupertinoListTile CupertinoListTileChevron CupertinoLocalizations
CupertinoMagnifier CupertinoMenuAnchor CupertinoMenuAnimationStatusChangedCallback
CupertinoMenuDivider CupertinoMenuEntry CupertinoMenuItem CupertinoModalPopupRoute
CupertinoNavigationBar CupertinoNavigationBarBackButton CupertinoPage CupertinoPageRoute
CupertinoPageScaffold CupertinoPageScaffoldBackgroundColor CupertinoPageTransition
CupertinoPageTransitionsBuilder CupertinoPicker CupertinoPickerDefaultSelectionOverlay
CupertinoPopupSurface CupertinoRadio CupertinoRouteTransitionMixin CupertinoScrollBehavior
CupertinoScrollbar CupertinoSearchTextField CupertinoSegmentedControl CupertinoSheetRoute
CupertinoSheetTransition CupertinoSlider CupertinoSlidingSegmentedControl
CupertinoSliverNavigationBar CupertinoSliverRefreshControl CupertinoSpellCheckSuggestionsToolbar
CupertinoSwitch CupertinoTabBar CupertinoTabController CupertinoTabScaffold CupertinoTabView
CupertinoTextField CupertinoTextFormFieldRow CupertinoTextMagnifier CupertinoTextSelectionControls
CupertinoTextSelectionHandleControls CupertinoTextSelectionToolbar
CupertinoTextSelectionToolbarButton CupertinoTextThemeData CupertinoTheme CupertinoThemeData
CupertinoThumbPainter CupertinoTimerPicker CupertinoTimerPickerMode CupertinoToolbarBuilder
CupertinoUserInterfaceLevel CupertinoUserInterfaceLevelData Curve Curve2D Curve2DSample CurveTween
CurvedAnimation Curves CustomMultiChildLayout CustomPaint CustomScrollView CustomSingleChildLayout
DataCell DataColumn DataColumnSortCallback DataRow DataTable DataTableSource DataTableTheme
DataTableThemeData DatePickerDateOrder DatePickerDateTimeOrder DatePickerDialog DatePickerEntryMode
DatePickerMode DatePickerTheme DatePickerThemeData DateRangePickerDialog DateTimeRange DateUtils
DayPeriod DebugCreator DecoderBufferCallback DecoratedBox DecoratedBoxTransition DecoratedSliver
Decoration DecorationImage DecorationImagePainter DecorationTween DefaultAssetBundle
DefaultCupertinoLocalizations DefaultMaterialLocalizations DefaultPlatformMenuDelegate
DefaultSelectionStyle DefaultTabController DefaultTextEditingShortcuts DefaultTextHeightBehavior
DefaultTextStyle DefaultTextStyleTransition DefaultTransitionDelegate DefaultWidgetsLocalizations
DelegatedTransitionBuilder DeletableChipAttributes DeleteCharacterIntent DeleteToLineBreakIntent
DeleteToNextWordBoundaryIntent DesktopTextSelectionControls DesktopTextSelectionToolbar
DesktopTextSelectionToolbarButton DesktopTextSelectionToolbarLayoutDelegate
DevToolsDeepLinkProperty DeviceOrientationBuilder DiagonalDragBehavior Dialog DialogRoute
DialogTheme DialogThemeData DialogWindow DialogWindowController DialogWindowControllerDelegate
DialogWindowControllerLinux DialogWindowControllerMacOS DialogWindowControllerWin32
DidRemovePageCallback DirectionalCaretMovementIntent DirectionalFocusAction DirectionalFocusIntent
DirectionalFocusTraversalPolicyMixin DirectionalTextEditingIntent Directionality
DisableWidgetInspectorScope DisabledChipAttributes DismissAction DismissDirection
DismissDirectionCallback DismissIntent DismissMenuAction DismissUpdateCallback DismissUpdateDetails
Dismissible DisplayFeatureSubScreen DisposableBuildContext Divider DividerTheme DividerThemeData
DoNothingAction DoNothingAndStopPropagationIntent DoNothingAndStopPropagationTextIntent
DoNothingIntent DragAnchorStrategy DragBoundary DragBoundaryDelegate DragEndCallback
DragScrollActivity DragTarget DragTargetAccept DragTargetAcceptWithDetails DragTargetBuilder
DragTargetDetails DragTargetLeave DragTargetMove DragTargetWillAccept
DragTargetWillAcceptWithDetails DragUpdateCallback Draggable DraggableCanceledCallback
DraggableDetails DraggableScrollableActuator DraggableScrollableController
DraggableScrollableNotification DraggableScrollableSheet Drawer DrawerAlignment DrawerButton
DrawerButtonIcon DrawerCallback DrawerController DrawerControllerState DrawerHeader DrawerTheme
DrawerThemeData DrivenScrollActivity DropRangeSliderValueIndicatorShape
DropSliderValueIndicatorShape DropdownButton DropdownButtonBuilder DropdownButtonFormField
DropdownButtonHideUnderline DropdownMenu DropdownMenuCloseBehavior DropdownMenuDecorationBuilder
DropdownMenuEntry DropdownMenuFormField DropdownMenuItem DropdownMenuTheme DropdownMenuThemeData
DualTransitionBuilder Durations DynamicSchemeVariant Easing EdgeDraggingAutoScroller EdgeInsets
EdgeInsetsDirectional EdgeInsetsGeometry EdgeInsetsGeometryTween EdgeInsetsTween EditableText
EditableTextContextMenuBuilder EditableTextState EditableTextTapOutsideIntent
EditableTextTapUpOutsideIntent ElasticInCurve ElasticInOutCurve ElasticOutCurve Element
ElementCreatedCallback ElementVisitor ElevatedButton ElevatedButtonTheme ElevatedButtonThemeData
ElevationOverlay EmptyTextSelectionControls EnableWidgetInspectorScope EndDrawerButton
EndDrawerButtonIcon EntryModeChangeCallback ErrorWidget ErrorWidgetBuilder EvaluationResult
ExactAssetImage ExcludeFocus ExcludeFocusTraversal ExcludeSemantics
ExitWidgetSelectionButtonBuilder ExpandIcon ExpandSelectionToDocumentBoundaryIntent
ExpandSelectionToLineBreakIntent Expanded Expansible ExpansibleBuilder ExpansibleComponentBuilder
ExpansibleController ExpansionPanel ExpansionPanelCallback ExpansionPanelHeaderBuilder
ExpansionPanelList ExpansionPanelRadio ExpansionTile ExpansionTileController ExpansionTileTheme
ExpansionTileThemeData ExpansionTileTransitionMode ExtendSelectionByCharacterIntent
ExtendSelectionToDocumentBoundaryIntent ExtendSelectionToLineBreakIntent
ExtendSelectionToNextParagraphBoundaryIntent
ExtendSelectionToNextParagraphBoundaryOrCaretLocationIntent ExtendSelectionToNextWordBoundaryIntent
ExtendSelectionToNextWordBoundaryOrCaretLocationIntent
ExtendSelectionVerticallyToAdjacentLineIntent ExtendSelectionVerticallyToAdjacentPageIntent
FabCenterOffsetX FabContainedOffsetY FabDockedOffsetY FabEndOffsetX FabFloatOffsetY
FabMiniOffsetAdjustment FabStartOffsetX FabTopOffsetY FadeForwardsPageTransitionsBuilder
FadeInImage FadeTransition FadeUpwardsPageTransitionsBuilder Feedback FileImage FilledButton
FilledButtonTheme FilledButtonThemeData FilterCallback FilterChip FittedBox FittedSizes
FixedExtentMetrics FixedExtentScrollController FixedExtentScrollPhysics FixedScrollMetrics Flex
Flexible FlexibleSpaceBar FlexibleSpaceBarSettings FlippedCurve FlippedTweenSequence
FloatingActionButton FloatingActionButtonAnimator FloatingActionButtonLocation
FloatingActionButtonTheme FloatingActionButtonThemeData FloatingHeaderSnapMode
FloatingLabelAlignment FloatingLabelBehavior Flow FlutterLogo FlutterLogoDecoration
FlutterLogoStyle Focus FocusAttachment FocusHighlightMode FocusHighlightStrategy FocusManager
FocusNode FocusOnKeyCallback FocusOnKeyEventCallback FocusOrder FocusScope FocusScopeNode
FocusTraversalGroup FocusTraversalOrder FocusTraversalPolicy FocusableActionDetector Form FormField
FormFieldBuilder FormFieldErrorBuilder FormFieldSetter FormFieldState FormFieldValidator FormState
FractionalOffset FractionalTranslation FractionallySizedBox FutureBuilder
GappedRangeSliderTrackShape GappedSliderTrackShape GenerateAppTitle GestureDetector
GestureRecognizerFactory GestureRecognizerFactoryConstructor GestureRecognizerFactoryInitializer
GestureRecognizerFactoryWithHandlers GlobalKey GlobalObjectKey GlowingOverscrollIndicator Gradient
GradientRotation GradientTransform GregorianCalendarDelegate GridPaper GridTile GridTileBar
GridView HSLColor HSVColor HWND HandleRangeSliderThumbShape HandleThumbShape Hero HeroController
HeroControllerScope HeroFlightDirection HeroFlightShuttleBuilder HeroMode HeroPlaceholderBuilder
HoldScrollActivity HourFormat HtmlElementFactory HtmlElementView HttpClientProvider
HttpRequestFactory IOSSystemContextMenuItem IOSSystemContextMenuItemCopy
IOSSystemContextMenuItemCustom IOSSystemContextMenuItemCut IOSSystemContextMenuItemLiveText
IOSSystemContextMenuItemLookUp IOSSystemContextMenuItemPaste IOSSystemContextMenuItemSearchWeb
IOSSystemContextMenuItemSelectAll IOSSystemContextMenuItemShare Icon IconAlignment IconButton
IconButtonTheme IconButtonThemeData IconData IconDataProperty IconTheme IconThemeData Icons
IdleScrollActivity IgnoreBaseline IgnorePointer Image ImageCache ImageCacheStatus ImageChunkEvent
ImageChunkListener ImageConfiguration ImageDecoderCallback ImageErrorListener
ImageErrorWidgetBuilder ImageFiltered ImageFrameBuilder ImageIcon ImageInfo ImageListener
ImageLoadingBuilder ImageProvider ImageRepeat ImageSizeInfo ImageStream ImageStreamCompleter
ImageStreamCompleterHandle ImageStreamListener ImgElementPlatformView ImplicitlyAnimatedWidget
ImplicitlyAnimatedWidgetState IndexedSemantics IndexedSlot IndexedStack IndexedWidgetBuilder
InheritedCupertinoTheme InheritedElement InheritedModel InheritedModelElement InheritedNotifier
InheritedTheme InheritedWidget InitialRouteListFactory Ink InkDecoration InkFeature InkHighlight
InkResponse InkRipple InkSparkle InkSplash InkWell InlineSpan InlineSpanSemanticsInformation
InlineSpanVisitor InputBorder InputChip InputCounterWidgetBuilder InputDatePickerFormField
InputDecoration InputDecorationTheme InputDecorationThemeData InputDecorator InspectorButton
InspectorButtonVariant InspectorReferenceData InspectorSelection InspectorSelectionChangedCallback
InspectorSerializationDelegate IntTween Intent InteractiveInkFeature InteractiveInkFeatureFactory
InteractiveViewer InteractiveViewerWidgetBuilder Interval IntrinsicHeight IntrinsicWidth KeepAlive
KeepAliveHandle KeepAliveNotification KeyEventResult KeySet KeyboardListener KeyedSubtree
LabeledGlobalKey LabeledTapTargetEvaluation LayoutBuilder LayoutChangedNotification LayoutId
LayoutWidgetBuilder LeafRenderObjectElement LeafRenderObjectWidget LexicalFocusOrder LicensePage
LimitedBox LinearBorder LinearBorderEdge LinearGradient LinearProgressIndicator ListBody ListTile
ListTileControlAffinity ListTileStyle ListTileTheme ListTileThemeData ListTileTitleAlignment
ListView ListWheelChildBuilderDelegate ListWheelChildDelegate ListWheelChildListDelegate
ListWheelChildLoopingListDelegate ListWheelElement ListWheelScrollView ListWheelViewport
ListenableBuilder Listener LiveTextInputStatus LiveTextInputStatusNotifier LocalHistoryEntry
LocalHistoryRoute LocaleListResolutionCallback LocaleResolutionCallback Localizations
LocalizationsDelegate LocalizationsResolver LockState LogicalKeySet LongPressDraggable
LookupBoundary Magnifier MagnifierBuilder MagnifierController MagnifierDecoration MagnifierInfo
Material MaterialAccentColor MaterialApp MaterialBanner MaterialBannerClosedReason
MaterialBannerTheme MaterialBannerThemeData MaterialBasedCupertinoThemeData MaterialButton
MaterialColor MaterialGap MaterialInkController MaterialLocalizations MaterialPage
MaterialPageRoute MaterialPointArcTween MaterialPropertyResolver MaterialRectArcTween
MaterialRectCenterArcTween MaterialRouteTransitionMixin MaterialScrollBehavior MaterialSlice
MaterialState MaterialStateBorderSide MaterialStateColor MaterialStateMixin
MaterialStateMouseCursor MaterialStateOutlineInputBorder MaterialStateOutlinedBorder
MaterialStateProperty MaterialStatePropertyAll MaterialStateTextStyle
MaterialStateUnderlineInputBorder MaterialStatesController MaterialTapTargetSize
MaterialTextSelectionControls MaterialTextSelectionHandleControls MaterialType Matrix4Tween
MatrixTransition MatrixUtils MediaQuery MediaQueryData MemoryImage MenuAcceleratorCallbackBinding
MenuAcceleratorChildBuilder MenuAcceleratorLabel MenuAnchor MenuAnchorChildBuilder MenuBar
MenuBarTheme MenuBarThemeData MenuButtonTheme MenuButtonThemeData MenuController MenuItemButton
MenuItemSerializableIdGenerator MenuSerializableShortcut MenuStyle MenuTheme MenuThemeData
MergeSemantics MergeableMaterial MergeableMaterialItem MetaData MinimumNonTextContrastEvaluation
MinimumTapTargetEvaluation MinimumTextContrastEvaluation ModalBarrier ModalBottomSheetRoute
ModalRoute MouseRegion MoveExitWidgetSelectionButtonBuilder MultiChildRenderObjectElement
MultiChildRenderObjectWidget MultiFrameImageStreamCompleter
MultiSelectableSelectionContainerDelegate NavigationBar NavigationBarBottomMode NavigationBarTheme
NavigationBarThemeData NavigationDestination NavigationDestinationLabelBehavior NavigationDrawer
NavigationDrawerDestination NavigationDrawerTheme NavigationDrawerThemeData NavigationIndicator
NavigationMode NavigationNotification NavigationRail NavigationRailDestination
NavigationRailLabelType NavigationRailTheme NavigationRailThemeData NavigationToolbar Navigator
NavigatorFinderCallback NavigatorObserver NavigatorPopHandler NavigatorState NestedScrollView
NestedScrollViewHeaderSliversBuilder NestedScrollViewState NestedScrollViewViewport NetworkImage
NetworkImageLoadException NeverScrollableScrollPhysics NextFocusAction NextFocusIntent
NoDefaultCupertinoThemeData NoSplash NotchedShape NotifiableElementMixin Notification
NotificationListener NotificationListenerCallback NullableIndexedWidgetBuilder NumericFocusOrder
ObjectKey ObstructingPreferredSizeWidget Offstage OnInvokeCallback OnKeyEventCallback
OneFrameImageStreamCompleter Opacity OpenUpwardsPageTransitionsBuilder OptionsViewOpenDirection
OrderedTraversalPolicy Orientation OrientationBuilder OrientationWidgetBuilder OutlineInputBorder
OutlinedBorder OutlinedButton OutlinedButtonTheme OutlinedButtonThemeData OvalBorder OverflowBar
OverflowBarAlignment OverflowBox Overlay OverlayChildLayoutBuilder OverlayChildLocation
OverlayEntry OverlayPortal OverlayPortalController OverlayRoute OverlayState OverlayVisibilityMode
OverscrollIndicatorNotification OverscrollNotification Padding PaddleRangeSliderValueIndicatorShape
PaddleSliderValueIndicatorShape Page PageController PageMetrics PageRoute PageRouteBuilder
PageRouteFactory PageScrollPhysics PageStorage PageStorageBucket PageStorageKey
PageTransitionsBuilder PageTransitionsTheme PageView PaginatedDataTable PaginatedDataTableState
PaintImageCallback PaintRangeValueIndicator PaintValueIndicator PaintingBinding PanAxis
ParametricCurve ParentDataElement ParentDataWidget PasteTextIntent PerformanceOverlay
PersistentBottomSheetController PhysicalModel PhysicalShape PinnedHeaderSliver Placeholder
PlaceholderDimensions PlaceholderSpan PlatformAdaptiveIcons PlatformMenu PlatformMenuBar
PlatformMenuDelegate PlatformMenuItem PlatformMenuItemGroup PlatformProvidedMenuItem
PlatformProvidedMenuItemType PlatformRouteInformationProvider PlatformSelectableRegionContextMenu
PlatformViewCreationParams PlatformViewLink PlatformViewSurface PlatformViewSurfaceFactory PopEntry
PopInvokedCallback PopInvokedWithResultCallback PopNavigatorRouterDelegateMixin PopPageCallback
PopResultCallback PopScope PopupMenuButton PopupMenuButtonState PopupMenuCanceled PopupMenuDivider
PopupMenuEntry PopupMenuItem PopupMenuItemBuilder PopupMenuItemSelected PopupMenuItemState
PopupMenuPosition PopupMenuPositionBuilder PopupMenuTheme PopupMenuThemeData PopupRoute PopupWindow
PopupWindowController PopupWindowControllerDelegate PopupWindowControllerLinux
PopupWindowControllerMacOS PopupWindowControllerWin32 Positioned PositionedDirectional
PositionedTransition PredictiveBackFullscreenPageTransitionsBuilder
PredictiveBackPageTransitionsBuilder PredictiveBackRoute PreferredSize PreferredSizeWidget
PreviousFocusAction PreviousFocusIntent PrimaryScrollController PrioritizedAction
PrioritizedIntents ProgressIndicator ProgressIndicatorTheme ProgressIndicatorThemeData
ProxyAnimation ProxyElement ProxyWidget RadialGradient Radio RadioBuilder RadioClient RadioGroup
RadioGroupRegistry RadioListTile RadioMenuButton RadioTheme RadioThemeData RangeLabels
RangeMaintainingScrollPhysics RangeSlider RangeSliderThumbShape RangeSliderTickMarkShape
RangeSliderTrackShape RangeSliderValueIndicatorShape RangeThumbSelector RangeValues RawAutocomplete
RawChip RawDialogRoute RawDialogRouteBuilder RawGestureDetector RawGestureDetectorState RawImage
RawKeyboardListener RawMagnifier RawMaterialButton RawMenuAnchor RawMenuAnchorChildBuilder
RawMenuAnchorCloseRequestedCallback RawMenuAnchorGroup RawMenuAnchorOpenRequestedCallback
RawMenuAnchorOverlayBuilder RawMenuOverlayInfo RawRadio RawScrollbar RawScrollbarState RawTooltip
RawTooltipState RawView RawWebImage ReadingOrderTraversalPolicy RebuildDirtyWidgetCallback
RectCallback RectTween RectangularRangeSliderTrackShape RectangularRangeSliderValueIndicatorShape
RectangularSliderTrackShape RectangularSliderValueIndicatorShape RedoTextIntent RefreshCallback
RefreshControlIndicatorBuilder RefreshIndicator RefreshIndicatorMode RefreshIndicatorState
RefreshIndicatorStatus RefreshIndicatorTriggerMode RefreshProgressIndicator
RegisterServiceExtensionCallback RegisterViewFactory RegularWindow RegularWindowController
RegularWindowControllerDelegate RegularWindowControllerLinux RegularWindowControllerMacOS
RegularWindowControllerWin32 RelativePositionedTransition RelativeRectTween
RenderAbstractLayoutBuilderMixin RenderComparison RenderConstrainedLayoutBuilder
RenderNestedScrollViewViewport RenderObjectElement RenderObjectToWidgetAdapter
RenderObjectToWidgetElement RenderObjectWidget RenderSliverOverlapAbsorber
RenderSliverOverlapInjector RenderTapRegion RenderTapRegionSurface RenderTreeRootElement
RenderTwoDimensionalViewport RenderWebImage ReorderCallback ReorderDragBoundaryProvider
ReorderItemProxyDecorator ReorderableDelayedDragStartListener ReorderableDragStartListener
ReorderableList ReorderableListState ReorderableListView RepaintBoundary RepeatMode
RepeatingAnimationBuilder ReplaceTextIntent RequestFocusAction RequestFocusIntent ResizeImage
ResizeImageKey ResizeImagePolicy RestorableBool RestorableBoolN RestorableChangeNotifier
RestorableCupertinoTabController RestorableDateTime RestorableDateTimeN RestorableDouble
RestorableDoubleN RestorableEnum RestorableEnumN RestorableInt RestorableIntN RestorableListenable
RestorableNum RestorableNumN RestorableProperty RestorableRouteBuilder RestorableRouteFuture
RestorableString RestorableStringN RestorableTextEditingController RestorableTimeOfDay
RestorableValue RestorationMixin RestorationScope ReverseAnimation ReverseTween RichText
RootBackButtonDispatcher RootElement RootElementMixin RootRenderObjectElement RootRestorationScope
RootWidget RotatedBox RotationTransition RoundRangeSliderThumbShape RoundRangeSliderTickMarkShape
RoundSliderOverlayShape RoundSliderThumbShape RoundSliderTickMarkShape
RoundedRectRangeSliderTrackShape RoundedRectRangeSliderValueIndicatorShape
RoundedRectSliderTrackShape RoundedRectSliderValueIndicatorShape RoundedRectangleBorder
RoundedSuperellipseBorder Route RouteAware RouteCompletionCallback RouteFactory RouteInformation
RouteInformationParser RouteInformationProvider RouteInformationReportingType RouteListFactory
RouteObserver RoutePageBuilder RoutePopDisposition RoutePredicate RoutePresentationCallback
RouteSettings RouteTransitionRecord RouteTransitionsBuilder Router RouterConfig RouterDelegate Row
SafeArea SatelliteWindow SatelliteWindowController SatelliteWindowControllerDelegate SawTooth
Scaffold ScaffoldFeatureController ScaffoldGeometry ScaffoldMessenger ScaffoldMessengerState
ScaffoldPrelayoutGeometry ScaffoldState ScaleTransition ScriptCategory ScrollAction ScrollActivity
ScrollActivityDelegate ScrollAwareImageProvider ScrollBehavior ScrollConfiguration ScrollContext
ScrollController ScrollControllerCallback ScrollDecelerationRate ScrollDragController
ScrollEndNotification ScrollHoldController ScrollIncrementCalculator ScrollIncrementDetails
ScrollIncrementType ScrollIntent ScrollMetrics ScrollMetricsNotification ScrollNotification
ScrollNotificationCallback ScrollNotificationObserver ScrollNotificationObserverState
ScrollNotificationPredicate ScrollPhysics ScrollPosition ScrollPositionAlignmentPolicy
ScrollPositionWithSingleContext ScrollStartNotification ScrollToDocumentBoundaryIntent
ScrollUpdateNotification ScrollView ScrollViewKeyboardDismissBehavior Scrollable ScrollableDetails
ScrollableState ScrollableWidgetBuilder Scrollbar ScrollbarOrientation ScrollbarPainter
ScrollbarTheme ScrollbarThemeData SearchAnchor SearchAnchorChildBuilder SearchBar SearchBarTheme
SearchBarThemeData SearchCallback SearchController SearchDelegate SearchViewTheme
SearchViewThemeData SegmentedButton SegmentedButtonState SegmentedButtonTheme
SegmentedButtonThemeData SelectAction SelectAllTextIntent SelectIntent SelectableChipAttributes
SelectableDayForRangePredicate SelectableDayPredicate SelectableRegion
SelectableRegionContextMenuBuilder SelectableRegionSelectionStatus
SelectableRegionSelectionStatusScope SelectableRegionState SelectableText SelectionArea
SelectionAreaState SelectionChangedCallback SelectionContainer SelectionContainerDelegate
SelectionDetails SelectionListener SelectionListenerNotifier SelectionOverlay
SelectionOverlayBuilder SelectionRegistrarScope SemanticFormatterCallback SemanticIndexCallback
Semantics SemanticsDebugger SemanticsGestureDelegate SensitiveContent SensitiveContentHost
ShaderMask ShaderWarmUp ShaderWarmUpImageCallback ShaderWarmUpPictureCallback ShapeBorder
ShapeBorderTween ShapeDecoration ShapedInputBorder SharedAppData SharedAppDataInitCallback
ShortcutActivator ShortcutManager ShortcutMapProperty ShortcutRegistrar ShortcutRegistry
ShortcutRegistryEntry ShortcutSerialization Shortcuts ShowValueIndicator ShrinkWrappingViewport
SimpleDialog SimpleDialogOption SingleActivator SingleChildRenderObjectElement
SingleChildRenderObjectWidget SingleChildScrollView SingleTickerProviderStateMixin
SizeChangedLayoutNotification SizeChangedLayoutNotifier SizeTransition SizeTween SizedBox
SizedOverflowBox SlideTransition Slider SliderComponentShape SliderInteraction SliderTheme
SliderThemeData SliderTickMarkShape SliderTrackShape SliverAnimatedGrid SliverAnimatedGridState
SliverAnimatedList SliverAnimatedListState SliverAnimatedOpacity SliverAppBar
SliverChildBuilderDelegate SliverChildDelegate SliverChildListDelegate SliverConstrainedCrossAxis
SliverCrossAxisExpanded SliverCrossAxisGroup SliverEnsureSemantics SliverFadeTransition
SliverFillRemaining SliverFillViewport SliverFixedExtentList SliverFloatingHeader SliverGrid
SliverIgnorePointer SliverLayoutBuilder SliverLayoutWidgetBuilder SliverList SliverMainAxisGroup
SliverMultiBoxAdaptorElement SliverMultiBoxAdaptorWidget SliverOffstage SliverOpacity
SliverOverlapAbsorber SliverOverlapAbsorberHandle SliverOverlapInjector SliverPadding
SliverPersistentHeader SliverPersistentHeaderDelegate SliverPrototypeExtentList
SliverReorderableList SliverReorderableListState SliverResizingHeader SliverSafeArea
SliverSemantics SliverToBoxAdapter SliverVariedExtentList SliverVisibility
SliverWithKeepAliveWidget SlottedContainerRenderObjectMixin SlottedMultiChildRenderObjectWidget
SlottedMultiChildRenderObjectWidgetMixin SlottedRenderObjectElement SnackBar SnackBarAction
SnackBarBehavior SnackBarClosedReason SnackBarTheme SnackBarThemeData SnapshotController
SnapshotMode SnapshotPainter SnapshotWidget Spacer SpellCheckConfiguration
SpellCheckSuggestionsToolbar SpellCheckSuggestionsToolbarLayoutDelegate Split Stack StadiumBorder
StandardComponentType StandardFabLocation StarBorder State StateSetter StatefulBuilder
StatefulElement StatefulWidget StatefulWidgetBuilder StatelessElement StatelessWidget
StaticSelectionContainerDelegate StatusTransitionWidget Step StepIconBuilder StepState StepStyle
StepTween Stepper StepperType StreamBuilder StreamBuilderBase StretchEffect StretchMode
StretchingOverscrollIndicator StrutStyle SubmenuButton SuggestionsBuilder SweepGradient Switch
SwitchListTile SwitchTheme SwitchThemeData SystemContextMenu SystemTextScaler Tab TabAlignment
TabBar TabBarIndicatorSize TabBarScrollController TabBarTheme TabBarThemeData TabBarView
TabController TabIndicatorAnimation TabPageSelector TabPageSelectorIndicator TabValueChanged Table
TableCell TableRow TableRowInkWell TapBehaviorButtonBuilder TapRegion TapRegionCallback
TapRegionRegistry TapRegionSurface TapRegionUpCallback TappableChipAttributes Text
TextAlignVertical TextButton TextButtonTheme TextButtonThemeData TextEditingController TextField
TextFieldTapRegion TextFormField TextMagnifier TextMagnifierConfiguration TextOverflow TextPainter
TextScaler TextSelectionControls TextSelectionGestureDetector TextSelectionGestureDetectorBuilder
TextSelectionGestureDetectorBuilderDelegate TextSelectionHandleControls TextSelectionOverlay
TextSelectionTheme TextSelectionThemeData TextSelectionToolbar TextSelectionToolbarAnchors
TextSelectionToolbarLayoutDelegate TextSelectionToolbarTextButton TextSpan TextStyle TextStyleTween
TextTheme TextWidthBasis Texture Theme ThemeData ThemeDataTween ThemeExtension ThemeMode
ThreePointCubic Threshold Thumb TickerMode TickerModeData TickerProviderStateMixin TimeOfDay
TimeOfDayFormat TimePickerDialog TimePickerEntryMode TimePickerTheme TimePickerThemeData Title
TitleEvaluation ToggleButtons ToggleButtonsTheme ToggleButtonsThemeData ToggleablePainter
ToggleableStateMixin ToolbarBuilder ToolbarItemsParentData ToolbarOptions Tooltip
TooltipComponentBuilder TooltipPositionContext TooltipPositionDelegate TooltipState TooltipTheme
TooltipThemeData TooltipTriggerMode TooltipTriggeredCallback TooltipVisibility TooltipWindow
TooltipWindowController TooltipWindowControllerDelegate TooltipWindowControllerLinux
TooltipWindowControllerMacOS TooltipWindowControllerWin32 TrackingScrollController
TrainHoppingAnimation Transform TransformCallback TransformProperty TransformationController
TransitionBuilder TransitionDelegate TransitionRoute TransposeCharactersIntent TraversalDirection
TraversalEdgeBehavior TraversalRequestFocusCallback TreeSliver TreeSliverController TreeSliverNode
TreeSliverNodeBuilder TreeSliverNodeCallback TreeSliverRowExtentBuilder TreeSliverStateMixin Tween
TweenAnimationBuilder TweenConstructor TweenSequence TweenSequenceItem TweenVisitor
TwoDimensionalChildBuilderDelegate TwoDimensionalChildDelegate TwoDimensionalChildListDelegate
TwoDimensionalChildManager TwoDimensionalIndexedWidgetBuilder TwoDimensionalScrollView
TwoDimensionalScrollable TwoDimensionalScrollableState TwoDimensionalViewport
TwoDimensionalViewportBuilder TwoDimensionalViewportParentData Typography UiKitView
UnconstrainedBox UnderlineInputBorder UnderlineTabIndicator UndoHistory UndoHistoryController
UndoHistoryState UndoHistoryValue UndoTextIntent UnfocusDisposition UniqueWidget
UnlabeledLeafNodeEvaluation UnmanagedRestorationScope UpdateSelectionIntent
UserAccountsDrawerHeader UserScrollNotification ValueListenableBuilder ValueListenableTransformer
ValueWidgetBuilder VerticalDirection VerticalDivider View ViewAnchor ViewBuilder ViewCollection
Viewport ViewportBuilder ViewportElementMixin ViewportNotificationMixin Violation Visibility
VisualDensity VoidCallbackAction VoidCallbackIntent WeakMap WebBrowserDetection
WebHtmlElementStrategy WebImageInfo Widget WidgetBuilder WidgetInspector WidgetInspectorService
WidgetInspectorServiceExtensions WidgetOrderTraversalPolicy WidgetPropertyResolver WidgetSpan
WidgetState WidgetStateBorderSide WidgetStateColor WidgetStateInputBorder WidgetStateMap
WidgetStateMapper WidgetStateMouseCursor WidgetStateOutlinedBorder WidgetStateProperty
WidgetStatePropertyAll WidgetStateTextStyle WidgetStatesConstraint WidgetStatesController
WidgetToRenderBoxAdapter WidgetsApp WidgetsBinding WidgetsBindingObserver WidgetsFlutterBinding
WidgetsLocalizations WidgetsServiceExtensions WillPopCallback WillPopScope WindowControllerLinux
WindowControllerMacOS WindowControllerWin32 WindowEntry WindowManager WindowPositioner
WindowPositionerAnchor WindowPositionerConstraintAdjustment WindowRegistry WindowScope
WindowingOwner WindowingOwnerLinux WindowingOwnerMacOS WindowingOwnerWin32 WordBoundary Wrap
YearPicker ZoomPageTransitionsBuilder`;

/** dart:core / dart:async names a component must not shadow either. */
const DART_CORE_NAMES = 'Object Type Function Record Null Never String int double num bool List Map Set Iterable Iterator Duration DateTime Uri Error Exception Future Stream Symbol Pattern RegExp Match Comparable Enum Invocation Sink StackTrace Stopwatch Expando WeakReference Finalizer Timer Zone Completer';

/** Web globals / framework exports a hoisted React component must not shadow. */
const WEB_RESERVED_NAMES = 'Image Link Script Head Html Fragment Suspense StrictMode Component PureComponent Profiler Option Audio Video Text Node Element Event Response Request Headers URL Map Set Date Error Promise Symbol Proxy Array Object String Number Boolean Function JSON Math Navigate Route Routes Outlet Router Form Document Window File Blob Worker Notification History Location Storage Range Selection';

export const FLUTTER_SDK_NAMES: ReadonlySet<string> = new Set(`${FLUTTER_SDK_NAME_LIST} ${DART_CORE_NAMES}`.split(/\s+/).filter(Boolean));
export const WEB_RESERVED: ReadonlySet<string> = new Set(WEB_RESERVED_NAMES.split(/\s+/).filter(Boolean));

/** True when a component class name would shadow an SDK / platform symbol on this framework. */
export function shadowsSdkName(name: string, framework: string): boolean {
  return (framework || 'flutter').toLowerCase() === 'flutter' ? FLUTTER_SDK_NAMES.has(name) : WEB_RESERVED.has(name);
}
