// GENERATED by relay-server asset pass — do not edit by hand.
// Semantic names → bundled asset paths. Import `assets` and reference
// these instead of hard-coding strings or substituting icon-font glyphs.

export const assets = {
  searchIcon: 'assets/icons/search_icon.svg',
  mapDark: 'assets/images/map_dark.png',
  promoBanner: 'assets/images/promo_banner.png',
  userAvatar: 'assets/images/user_avatar.png',
} as const;

export type AssetName = keyof typeof assets;
