// GENERATED by relay-server asset pass — do not edit by hand.
// Semantic names → the URL each design asset is SERVED at (public/assets/…
// is served at /assets/…). Import `assets` and use the value directly —
// `<img src={assets.x} />` — never a hard-coded path or a redrawn glyph.

export const assets = {
  searchIcon: '/assets/icons/search_icon.svg',
  mapDark: '/assets/images/map_dark.png',
  promoBanner: '/assets/images/promo_banner.png',
  userAvatar: '/assets/images/user_avatar.png',
} as const;

export type AssetName = keyof typeof assets;
